#%RAML 0.8
---
title: Compra venta de gatitos
version: v1
#baseUri: http:/localhost:8080/{version}/
baseUri: http://mocksvc.mulesoft.com/mocks/08923082-658e-41d9-a5e5-d1eacb438183
mediaType: application/json
