#%RAML 0.8
---
title: Gatitos API
version: v1
baseUri: http:/localhost:8080/{version}/
mediaType: application/json
schemas:
  - cat: !include cat.schema.json
  - cats: !include cats.schema.json
  - error: !include error.schema.json
resourceTypes:
  - collection:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>>
        queryParameters:
          search:
            displayName: Search
            type: string
            required: false

      post:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>
        body:
          schema : <<resourcePathName | !singularize>>
          
  - member:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>
        queryParameters:
          filterBy:
            displayName: FilterBy
            type: string
            required: false

      put:
        responses:
          201:
            body:
              schema: <<resourcePathName | !singularize>>>
        body:
          schema : <<resourcePathName | !singularize>>
    

/cats:
  displayName: Gatitos
  description: Compra, venta y renta de gatitos
  type: collection
    
  /{catId}:
    displayName: GatitoById
    description: Un gatito en especifico
    type: member
  

